### ISSUE TITLE
如果我的加载器是Requirejs，修改起来麻烦吗？

### ISSUE THREAD

**Issue by rangerch** [aralejs/aralejs.org#338]
项目的加载器是使用AMD规范的，可以兼容吗？

**Comment by piaer** [comment]
你好，如何把arale改成amd的

**Comment by lizzie** [comment]
楼上抛弃 XMD 吧，拥抱 commonjs 规范。编译打包后成最终的资源文件，可以试下 [spmjs](http://spmjs.io/)
