### ISSUE TITLE
spm安装的js无法导入

### ISSUE THREAD

**Issue by LeeDaYe** [aralejs/aralejs.org#363]
你好，我在使用arale的时候，用spm install 命令安装的js文件，然后用seajs.use加载安装的js文件，都会报错，原因就是require, exports, module这些变量未定义。
        我在spm安装的js最外层添加define(function(require,exports,module){})就可以了，请问你们这个是怎么处理的？

**Comment by yunfour** [comment]
你确定你引入了seajs的脚步文件？？

**Comment by LeeDaYe** [comment]
我确定引入了的，用的cdn的地址，我仅改变spm安装的js文件，网页就能正常运行。我对比你们arale的5分钟上手的的例子中加载的js，发现js最外层少了define的封装，加上就可以了

**Comment by afc163** [comment]
spm 中下载的文件均为 CommonJS 源码，需要构建后才能正式调用。

但是我们也提供了几种方式来线下调试 CommonJS 源码。

具体可以看下：https://github.com/seajs/seajs/issues/1330

**Comment by afc163** [comment]
Arale 中的模块开发方式实际上就是一种调试源码的方式：http://aralejs.org/docs/develop-components.html#%E6%9C%AC%E5%9C%B0%E8%B0%83%E8%AF%95

**Comment by afc163** [comment]
补充了下文档：[调试 CommonJS 源码](http://aralejs.org/docs/develop-components.html#%E8%B0%83%E8%AF%95-commonjs-%E6%BA%90%E7%A0%81)

**Comment by LeeDaYe** [comment]
谢谢，刚刚开了，明白了！
